name = "hobe-design-house"
main = "server/index.ts"
compatibility_date = "2024-02-27"

[build]
command = "npm run build"
cwd = "."
watch_dir = "src"

[site]
bucket = "./dist"

# Development environment
[env.development]
name = "hobe-design-house-dev"
vars = { NODE_ENV = "development" }

# Production environment
[env.production]
name = "hobe-design-house-prod"
vars = { 
  NODE_ENV = "production",
  DATABASE_URL = "postgresql://neondb_owner:npg_KVNjdcf0v5RB@ep-sweet-fog-a86epj7s-pooler.eastus2.azure.neon.tech/neondb?sslmode=require"
}
routes = [
  { pattern = "/*", zone_name = "your-domain.com" }
]

# Configure build output directory
[build.upload]
format = "service-worker"
dir = "dist"
main = "./dist/server/index.js"